server:
  port: 8088
  servlet:
    #设置项目根路径
    context-path: /community
#关闭thymeleaf模板缓存
spring:
  thymeleaf:
    cache: false
#  profiles:
#    # 选择环境
#    active: @activatedProperties@
  #配置数据库连接池
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/community?characterEncoding=utf-8&useSSL=false&serverTimezone=Hongkong
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 15
      minimum-idle: 5
      idle-timeout: 30000
  mail:
    host: smtp.sina.com
    port: 465
    username: alexlqx@sina.com
    password: 65d0ee3a806ff5ff
    protocol: smtps
    properties:
      mail:
        smtp:
          ssl:
            enable: true
  #配置上传文件的大小
#  http:
#    multipart:
#      max-file-size: 10MB
#      max-request-size: 10MB
  redis:
    database: 11
    host: localhost
    port: 6379
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      # kafka组id
      group-id: community-consumer-group
      # 是否自动提交消费者偏移量
      enable-auto-commit: true
      auto-commit-interval: 3000

  data:
    elasticsearch:
      cluster-name: nowcoder
      cluster-nodes: 127.0.0.1:9300
#mybatis相关配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.nowcoder.community.entity
  configuration:
    #设置id主键自增
    use-generated-keys: true
    #数据库字段名称与类属性名称对应
    map-underscore-to-camel-case: true
#logger配置
logging:
  level:
    com:
      nowcoder:
        community: debug
  # 设置logback.xml位置
  config: classpath:logback.xml

# 自定义网站域名
community:
  path:
#设置域名
    domain: http://localhost:8088/
# 配置文件上传位置
    upload: d:/work/data/upload